services:
  postgres:
    image: postgres:16-alpine
    container_name: projectme-Database
    environment:
      POSTGRES_DB: projectme_db
      POSTGRES_USER: projectme_user
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U projectme_user -d projectme_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      dockerfile: Dockerfile
    container_name: projectme-backend
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: ""
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:

